### ISSUE TITLE
Where are ES2015 samples ?

### ISSUE THREAD

**Issue by k33g** [luijar/functional-programming-js#1]
Hello @luijar, I' reading your book (very instructive, I ❤️  it), but I can't find the ES2015 samples like `class Maybe`.

**Comment by k33g** [comment]
I'm working on a talk about Functional Programming for newbies (as me) with JavaScript, and your book is a great help for me 👏

**Comment by luijar** [comment]
@k33g Rock on! Very glad to hear about this. If you have any questions don't hesitate to ask, and if anyone is interested in the book you can share this discount code with them: **39atencio**

**Comment by k33g** [comment]
thx a lot @luijar  :)

**Comment by luijar** [comment]
Hey @k33g, 
I've updated the sample code up to CH05 all in ES6. I'm working on CHs 6, 7, and 8. Class Maybe should be in there now for the most part.
Sorry for the inconvenience.
Thanks!
