### ISSUE TITLE
Missing Code Samples

### ISSUE THREAD

**Issue by miketembo** [luijar/functional-programming-js#2]
cant find code samples

**Comment by luijar** [comment]
Hey @miketembo,
I apologize for that. I'm trying to find some time to update the repo with all of the latest code to match the chapter listings. 

Thanks!

**Comment by luijar** [comment]
Hey @miketembo,
Thanks for the feedback. All code samples up to CH05 are there now. I've organized the repo a bit, so it should be straightforward to find the code samples. 
If you have Node installed, then you can just run the code listings as unit tests. 
I'm working on wrapping up Chs 6, 7, and 8.
Thanks!

**Comment by luijar** [comment]
Code samples for all chapters added. They all run as Node unit test so that you can easily change them and run to get results. 
Closing this issue for now. Let me know if there is anything that I've missed.
