### ISSUE TITLE
Update book repo

### ISSUE THREAD

**Issue by peterschussheim** [luijar/functional-programming-js#4]
Hi,

Love the book but as others have mentioned in other issues and on the Manning forums, this repo is disappointing given it is part of a book that costs roughly $50.  If you are too busy to update the code, why not ask for help from the community here?

Thanks,
Peter

**Comment by luijar** [comment]
Hey Peter. 

Yup you're right. That's a good idea. I will update this ASAP. 

Thanks!

**Comment by luijar** [comment]
Hey @peterschussheim 
I've updated all code samples up to CH05. Please check it out and let me know, but it should be really straightforward now. All of the monad classes and their respective folders and matching the book code. Also, it's all using ES6. 

With Node, you can just run all the code listings as unit tests. 

I'm working on wrapping up Chs 6,7,8

Thanks and sorry for the inconvenience.

**Comment by luijar** [comment]
Code samples for all chapters added. They all run as Node unit test so that you can easily change them and run to get results. 
Closing this issue for now. Let me know if there is anything that I've missed.
Thanks again!

**Comment by peterschussheim** [comment]
@luijar Awesome, thanks for responding so quickly and great work on the book.
