### ISSUE TITLE
Test Fail To Run

### ISSUE THREAD

**Issue by winsonkwok** [luijar/functional-programming-js#9]
I'm using Qunit v1.0.0. All the test codes fail to run with following error:

 stack: ReferenceError: assert is not defined

Thus, we have to inject "the assert" into each test code. 

For example, the test code of 1.4 will become:

QUnit.test("Listing 1.4 Decomposing the showStudent program", function (assert) {...  <- put assert here

**Comment by luijar** [comment]
Hi @winsonkwok, 

I don't see that problem. I upgraded to QUnit 1.0.0 and all tests work for me. Did you run `npm install` ? 

I added some helper scripts so that you can just run,`npm run ch1` to run all Chater 1 tests, and so on for all chapters. 

They're all working for me.
